name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -q --no-cache-dir -e .[complete]
        python -m pip list
    - name: Lint with Pyflakes
      if: matrix.python-version == 3.10 && matrix.os == 'ubuntu-22.04'
      run: |
        python -m pyflakes .
    - name: Lint with Black
      if: matrix.python-version == 3.10 && matrix.os == 'ubuntu-22.04'
      run: |
        black --check --diff --verbose .
    - name: Check MANIFEST
      if: matrix.python-version == 3.10 && matrix.os == 'ubuntu-22.04'
      run: |
        check-manifest
    - name: Test with pytest
      run: |
        python -m pytest -r sx
    - name: Report coverage with Codecov
      if: github.event_name == 'push' && matrix.python-version == 3.10 && matrix.os == 'ubuntu-22.04'
      uses: codecov/codecov-action@master
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
